version: '3'

services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
  web:
    restart: always
    container_name: web
    build: .
    command: >
      sh -c "flask db upgrade &&
             flask run --host 0.0.0.0 --port 5000"
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - db
