"""Add unique constraint together fot site.url  and site.user_id

Revision ID: 0dde5edb4e07
Revises: a85e2d53a84b
Create Date: 2024-02-01 05:54:31.285945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dde5edb4e07'
down_revision = 'a85e2d53a84b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_name', type_='unique')
        batch_op.create_unique_constraint('unique_user_url', ['user_id', 'url'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_url', type_='unique')
        batch_op.create_unique_constraint('unique_user_name', ['user_id', 'name'])

    # ### end Alembic commands ###
