"""Make sites field created_at as server_default.

Revision ID: 12bfdc5ada65
Revises: 520401eb3fe6
Create Date: 2024-01-28 14:30:20.601679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12bfdc5ada65'
down_revision = '520401eb3fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_column('custom_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_url', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
