"""Make site.name & site.url n
ullable

Revision ID: 43ff11c70caa
Revises: db2e83715790
Create Date: 2024-02-01 04:17:26.067001

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "43ff11c70caa"
down_revision = "db2e83715790"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sites", schema=None) as batch_op:
        batch_op.create_unique_constraint("unique_site_url", ["url"])
        batch_op.create_unique_constraint("unique_site_name", ["name"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sites", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
