"""Update site model

Revision ID: 520401eb3fe6
Revises: 6cc1d9c61bb0
Create Date: 2024-01-27 21:06:54.863386

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "520401eb3fe6"
down_revision = "6cc1d9c61bb0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sites", schema=None) as batch_op:
        batch_op.add_column(sa.Column("original_url", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("custom_url", sa.String(), nullable=True))
        batch_op.drop_column("url")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sites", schema=None) as batch_op:
        batch_op.add_column(sa.Column("url", sa.VARCHAR(), nullable=False))
        batch_op.drop_column("custom_url")
        batch_op.drop_column("original_url")

    # ### end Alembic commands ###
