"""Remove site custom_url field

Revision ID: 9a25af8960ef
Revises: f840f4de6539
Create Date: 2024-01-29 21:01:01.280498

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9a25af8960ef"
down_revision = "f840f4de6539"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sites", schema=None) as batch_op:
        batch_op.drop_column("custom_url")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sites", schema=None) as batch_op:
        batch_op.add_column(sa.Column("custom_url", sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
