"""Update site

Revision ID: db2e83715790
Revises: 9edb8ee05546
Create Date: 2024-01-31 20:27:33.572157

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "db2e83715790"
down_revision = "9edb8ee05546"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sites", schema=None) as batch_op:
        batch_op.alter_column(
            "data_received",
            existing_type=sa.INTEGER(),
            type_=sa.Float(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sites", schema=None) as batch_op:
        batch_op.alter_column(
            "data_received",
            existing_type=sa.Float(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
