"""Rename site original_url field

Revision ID: ea4ff1151528
Revises: 9a25af8960ef
Create Date: 2024-01-29 22:34:51.036832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea4ff1151528'
down_revision = '9a25af8960ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(), nullable=False))
        batch_op.drop_column('original_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_url', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('url')

    # ### end Alembic commands ###
