"""Add custom_url to sites

Revision ID: f3c44bce517a
Revises: 12bfdc5ada65
Create Date: 2024-01-28 15:41:07.618464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c44bce517a'
down_revision = '12bfdc5ada65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_url', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_column('custom_url')

    # ### end Alembic commands ###
